#!/bin/bash
. $STYLEPP_DIR/stylepp_common

FILE=$TOP/.stylepp/long_lines
stylepp_skeleton $* stylepp_warn80 2>$FILE
chmod +x $FILE

if [ -z "`cat $FILE`" ]; then
  rm $FILE
  exit 0
else
  echo "Detected `cat $FILE | wc -l` lines longer than 80 characters."
  echo "Run $FILE to edit them in vim."
  echo
  exit 1
fi

