#!/bin/bash
. $STYLEPP_DIR/stylepp_common

git stash >/dev/null

stylepp_leading_spaces
SPACES=`git diff | grep "^+" | wc -l`
git reset --hard >/dev/null
stylepp_leading_tabs
TABS=`git diff | grep "^+" | wc -l`
git reset --hard >/dev/null

echo "# Lines changed when going to tabs:spaces $TABS:$SPACES"
if [ "$SPACES" -le "$TABS" ]; then
  echo stylepp_leading_spaces
else
  echo stylepp_leading_tabs
fi
git stash pop 2>/dev/null
