#!/bin/bash

for I in `find  -executable -type f | grep "\(\.c\|\.h\|\.cc\|\.cpp\|\.java\|\.adb\|\.ads\|\.f\|\.f90\|\.f95\|\.txt\|\.htm\|\.html\|\.tex\|\.texi\|\.ml\|\.mli\)$"`; do
  chmod -x $I
done
