#!/bin/bash
. $STYLEPP_DIR/stylepp_common
while read WORD; do
  if [ ! -z "`echo $WORD | awk '{print $1;}' | aspell list`" ]; then
    if [  -z "`echo $WORD | awk '{print $2;}' | aspell list`" ]; then
      echo "$WORD"
    fi
  fi
done
