#!/bin/bash
. $STYLEPP_DIR/stylepp_common
. $STYLEPP_DIR/stylepp_directory

for CUP in $*; do
  for I in $FILES; do
    if [ "${I: -2}" == ".c" ] || [ "${I: -4}" == ".cpp" ] || [ "${I: -3}" == ".cc" ] || [ "${I: -2}" == ".h" ]; then
      if $CUP $I <$I > $TMP_FMT; then
        diff -u $TMP_FMT $I >> /tmp/diff
        chmod $TMP_FMT --reference $I
        mv $TMP_FMT $I
      fi
    fi
  done
done

