#!/bin/bash

TOP=`git rev-parse --show-toplevel`
FILES=`mktemp`
DIC=`mktemp`
echo >$DIC
HISTORYDIR=$TOP/.stylepp/history
HISTORYDICTIONARY=$TOP/.stylepp/dictionary_history
mkdir $HISTORYDIR

git format-patch -o $HISTORYDIR `git log --pretty=format:%H | tail -1`

for FILE in $HISTORYDIR/*; do
  echo $FILE
  stylepp_typos_from_diff < $FILE >> $DIC
done

stylepp_spellcheck > /dev/null
stylepp_subtract_dictionary $DIC $TOP/.stylepp/words_code  | stylepp_format_dictionary | stylepp_filter_dictionary | stylepp_sortuniq  | stylepp_remove_ambiguous_dictionary | stylepp_clean_dictionary > $HISTORYDICTIONARY

#rm -r $HISTORYDIR

