#!/bin/bash
. $STYLEPP_DIR/stylepp_common

TMP_FILES=`mktemp`
TMP_FMT=`mktemp`

if [ "$1" == "--hook" ]; then
  shift 1
  # Hook version.
  TOP=`git rev-parse --show-toplevel`
  rm $TMP_FILES 2> /dev/null
  echo > $TMP_FILES
  for I in `git diff --name-only`; do
    I=$TOP/$I
    echo $I >> $TMP_FILES
  done
  FILES=`cat $TMP_FILES`
  rm $TMP_FILES
else
  FILES=`find`
fi

for CUP in stylepp_fix_comment; do
  for I in $FILES; do
    if [ "${I: -2}" == ".c" ] || [ "${I: -2}" == ".h" ] || [ "${I: -3}" == ".cc" ] || [ "${I: -4}" == ".cpp" ] || [ "${I: -2}" == ".S" ] || [ "${I: -5}" == ".java" ] || [ "${I: -4}" == ".adb" ] || [ "${I: -4}" == ".ads" ] || [ "${I: -2}" == ".f" ] || [ "${I: -4}" == ".f90" ] || [ "${I: -4}" == ".f95" ] || [ "${I: -3}" == ".py" ] || [ "${I: -3}" == ".sh" ] || [ "${I: -3}" == ".rb" ] || [ "${I: -4}" == ".txt" ] || [ "${I: -4}" == ".htm" ] || [ "${I: -5}" == ".html" ] || [ "${I: -4}" == ".tex" ] || [ "${I: -5}" == ".texi" ] || [ "${I: -3}" == ".ml" ] || [ "${I: -4}" == ".mli" ]; then
      if $CUP $I $* <$I > $TMP_FMT; then
        diff -u $TMP_FMT $I >> /tmp/diff
        chmod $TMP_FMT --reference $I
        mv $TMP_FMT $I
      fi
    fi
  done
done

# Cleanup.
rm $TMP_FMT 2>/dev/null
