#!/bin/bash
. $STYLEPP_DIR/stylepp_common

DIC=.stylepp/dictionary
mkdir $TOP/.stylepp 2> /dev/null

stylepp_spellcheck

if [ ! -f $DIR/maintained/dictionary_personal ]; then
  cp $DIR/maintained/dictionary_common $DIR/../maintained/dictionary_personal
fi

stylepp_subtract_dictionary $DIR/maintained/dictionary_wiki $TOP/.stylepp/words_code > $DIC
stylepp_fix_spell $*
git commit -a -m "Fix common typos."

#stylepp_subtract_dictionary $DIR/maintained/dictionary_names $TOP/.stylepp/words_code > DIC
#stylepp_fix_spell $*
#git commit -a -m "Fix capitalization."

stylepp_subtract_dictionary $DIR/maintained/dictionary_personal $TOP/.stylepp/words_code > $DIC
stylepp_fix_spell $*
git commit -a -m "Fix typos from personal list."

# Generates false positives.
stylepp_subtract_dictionary $DIR/maintained/dictionary_history $TOP/.stylepp/words_code > $DIC
stylepp_fix_spell $*
git commit -a -m "Fix typos from history list."

cp  $DIR/maintained/a_an_exceptions.txt $DIC
stylepp_skeleton stylepp_fix_a_an
git commit -a -m "Fix missplaced a/an."


stylepp_spellcheck
stylepp_dictionary

git commit -a -m "Fix typos."

# Now merge fixes to personal directory
TDICT=`mktemp`
cat dictionary $DIR/maintained/dictionary_personal | stylepp_format_dictionary | stylepp_sortuniq > $TDICT
cp $TDICT $DIR/maintained/dictionary_personal
rm $TDICT
