#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PATH=$PATH:$DIR/../bin:$DIR


for LINK in `stylepp_skeleton $* stylepp_extract_http_address 2>&1 | sort | uniq`; do
  if curl -f "$LINK" >/dev/null 2>/dev/null; then
    true
  else
    DEAD="true"
    echo Dead link: $LINK
  fi
done

if [ -z "$DEAD" ]; then
  exit 0
else
  echo
  exit 1
fi
