#!/bin/bash
. $STYLEPP_DIR/stylepp_common


cp $TOP/.stylepp/misspells $TOP/.stylepp/corrected
aspell -c $TOP/.stylepp/corrected
stylepp_make_dictionary $TOP/.stylepp/misspells $TOP/.stylepp/corrected > $TOP/.stylepp/dictionary

stylepp_fix_spell
