#!/bin/bash

#stylepp_spellcheck
TOP=`git rev-parse --show-toplevel`
FILES=`mktemp`
DIC=/tmp/dict
echo >$DIC
mkdir $TOP/.stylepp/history

git format-patch -o $TOP/.stylepp/history `git log --pretty=format:%H | tail -1` > $FILES

for FILE in $FILES; do
	stylepp_typos_from_diff < $FILE >> $DIC
done
cat $DIC | stylepp_sortuniq
rm -r $TOP/.stylepp/history

